# Generated by Django 4.2.7 on 2023-11-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('shop_store', models.BooleanField()),
                ('imageUrl', models.ImageField(default='../../Teashop/image/Rectangle.svg', upload_to='images')),
            ],
        ),
    ]
